export enum ATTENDANCE_ENUM {
    CLOCKIN = "CLOCKIN",
    CLOCKOUT = "CLOCKOUT"
}

export enum LEAVES_TYPE {
    CASUAL_AND_SICK = "CASUAL_AND_SICK",
    EARNED_LEAVES = "EARNED_LEAVES",
    OPTIONAL_HOLIDAY = "OPTIONAL_HOLIDAY",
    PATERNITY_LEAVES = "PATERNITY_LEAVES",
    MATERNITY_LEAVES = "MATERNITY_LEAVES",
    LEAVE_WITHOUT_PAY = "LEAVE_WITHOUT_PAY"
}